global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['prometheus:9090']


  - job_name: apache

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets:
          - apache-exporter:9117

  - job_name: mysql_exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
       - targets: ['mysql_exporter:9104']